### ISSUE TITLE
Bold font theorem environment

### ISSUE THREAD

**Issue by Reben80** [KurdishXeLaTeX/Support#2]
I found when you are using a theorem environment, the head of the theorem is not bold.  I tried both in Mac (TeXshop) and online (Overleaf). I used different fonts too.

**Comment by sinaahmadi** [comment]
This may be due to incomplete font forms. In addition to the regular form of a font, say `Yas.ttf`, you should have the other forms installed. Make sure you have the other files as well. See, for example, the [file for the `Yas` font](https://fontlibrary.org/en/font/yas).

Regarding Overleaf, if you are importing your own font, make sure you declare the new font family as described [here](https://www.overleaf.com/learn/latex/Questions/I_have_a_custom_font_I%27d_like_to_load_to_my_document._How_can_I_do_this%3F).

**Comment by sinaahmadi** [comment]
A set of fonts usable for Kurdish will be provided at [https://github.com/KurdishXeLaTeX/Support/tree/master/fonts](https://github.com/KurdishXeLaTeX/Support/tree/master/fonts).

Thanks.
